#!/bin/bash
##
# Call from within home directory of a new Python project. 
#
# usage:
#   newScalaProject project-name
# -> if project-name is not provided, prompts user for one
##

# Create directory structure
mkdir bin docs "$1" tests

declare -a FILES=(""$1"/__init__.py" "tests/__init__.py" "tests/"$1"_tests.py")

for file in "${FILES[@]}"; do
	echo "#!/usr/bin/env python" > "$file"
done

echo "
from nose.tools import *
import "$1"


def setup():
	print("Setting up")


def teardown():
	print("Tearing down")


def test_basic():
	print("Basic test")" >> tests/"$1"_tests.py
