#!/bin/bash

dir=${PWD##*/}
scalaVersion=$(scala -version 2>&1 | sed 's/Scala code runner version \([^ ]*\).*/\1/; 1q')

if [[ ${1+x} ]]; then name=$1; else name=$dir; fi 

mkdir -p src/{main,test}/{java,resources,scala}
mkdir lib project target

echo "name := \"$name\"
version := \"1.0\"
scalaVersion := \"$scalaVersion\"
libraryDependencies += \"org.scalatest\" %% \"scalatest\" % \"2.2.6\" % \"test\"
libraryDependencies += \"junit\" % \"junit\" % \"4.10\" % \"test\"" > build.sbt
